import type { Article, Review, Reviewer, DashboardStats, ReviewQueueItem } from './types';

export const mockArticles: Article[] = [
  {
    id: '1',
    headline: 'Government Announces Sweeping Tax Reform Package',
    publisher: 'The Daily Standard',
    date: '2026-02-15',
    content: `The government unveiled its most ambitious tax reform package in decades today, promising to restructure income brackets and corporate tax rates. Supporters call it a necessary modernization of an outdated system, while critics warn it disproportionately benefits the wealthy.\n\nThe proposal includes changes to capital gains taxation, estate taxes, and introduces new digital commerce levies. Economic analysts predict mixed outcomes depending on implementation timelines.\n\n"This is the most significant fiscal policy change we've seen in a generation," said Treasury officials during the press briefing. Opposition leaders quickly responded, calling the plan "a gift to corporate donors wrapped in populist rhetoric."\n\nThe bill is expected to face significant opposition in committee hearings scheduled for next month.`,
    politicalLeaning: 0.35,
    emotionalIntensity: 0.45,
    tribalActivation: 0.3,
    threatSignal: 0.2,
    sensationalism: 0.4,
    groupConflict: 0.35,
    biasExplanation: 'Moderate right-leaning framing detected. Language choice subtly favors the reform narrative while presenting opposition views with less detail. Use of "ambitious" and "modernization" carries positive connotations.',
    behaviouralAnalysis: 'The article employs framing techniques that position the reform as progressive while minimizing counterarguments. Threat-based language is minimal but tribal signaling appears in the "us vs them" structure of supporter/critic quotes.',
    highlightedSentences: [
      'Supporters call it a necessary modernization of an outdated system',
      'a gift to corporate donors wrapped in populist rhetoric',
    ],
  },
  {
    id: '2',
    headline: 'Climate Activists Block Major Highway in Protest',
    publisher: 'Metro News Network',
    date: '2026-02-14',
    content: `Hundreds of climate activists brought traffic to a standstill on the city's main arterial highway during morning rush hour, demanding immediate action on carbon emissions targets.\n\nThe protest, organized by the environmental coalition Green Future Now, resulted in dozens of arrests and hours of gridlock affecting thousands of commuters.\n\nProtest organizers defended the disruption: "We understand the inconvenience, but the climate crisis demands urgent attention. Business as usual is no longer acceptable."\n\nCommuters expressed frustration, with many taking to social media to criticize the tactics. Local business owners reported significant losses due to delivery delays.\n\nPolice deployed riot gear after tensions escalated near the downtown exit ramps.`,
    politicalLeaning: -0.5,
    emotionalIntensity: 0.72,
    tribalActivation: 0.65,
    threatSignal: 0.55,
    sensationalism: 0.6,
    groupConflict: 0.7,
    biasExplanation: 'Left-leaning framing that centers activist perspective while portraying commuter frustration as secondary. Emotionally charged language ("brought traffic to a standstill", "riot gear") amplifies the sense of conflict.',
    behaviouralAnalysis: 'High tribal activation through clear in-group/out-group framing. The article activates threat responses through crisis language and imagery of police confrontation. Group conflict is elevated by positioning activists against commuters.',
    highlightedSentences: [
      'Business as usual is no longer acceptable',
      'Police deployed riot gear after tensions escalated',
    ],
  },
  {
    id: '3',
    headline: 'New Study Reveals Social Media Impact on Teen Mental Health',
    publisher: 'Science Daily Report',
    date: '2026-02-13',
    content: `A comprehensive longitudinal study published today in the Journal of Adolescent Psychology finds a statistically significant correlation between social media usage patterns and declining mental health indicators among teenagers.\n\nThe study, conducted over five years across 12 countries with 50,000 participants, found that teens spending more than three hours daily on social media platforms showed 40% higher rates of anxiety and depression symptoms.\n\nResearchers noted important nuances: "Not all screen time is created equal. Passive consumption showed the strongest negative correlation, while creative and social interaction had more mixed results."\n\nTech industry representatives questioned the methodology, pointing to other societal factors that could explain the trends.`,
    politicalLeaning: -0.1,
    emotionalIntensity: 0.35,
    tribalActivation: 0.15,
    threatSignal: 0.4,
    sensationalism: 0.25,
    groupConflict: 0.2,
    biasExplanation: 'Relatively neutral framing with slight concern-oriented lean. The headline uses "reveals" which implies definitive findings, though the article itself includes appropriate caveats and alternative perspectives.',
    behaviouralAnalysis: 'Low tribal activation but moderate threat signaling through health-related concerns about children. The article maintains journalistic balance by including industry response and researcher nuances.',
    highlightedSentences: [
      '40% higher rates of anxiety and depression symptoms',
      'Not all screen time is created equal',
    ],
  },
  {
    id: '4',
    headline: 'Opposition Leader Calls Election Results "Stolen" Without Evidence',
    publisher: 'National Observer',
    date: '2026-02-12',
    content: `The opposition party leader took to national television last night to declare the recent municipal elections were "fundamentally compromised," despite election monitors from multiple independent organizations certifying the results.\n\nThe claims, which included allegations of ballot manipulation and voter suppression, have been repeatedly debunked by fact-checking organizations and election security experts.\n\n"We will not accept these fraudulent results," the leader declared to a rally of supporters. "The will of the people has been subverted by a corrupt system."\n\nPolitical analysts warn that such rhetoric undermines democratic institutions and could incite civil unrest. Several social media platforms have flagged the claims as misinformation.`,
    politicalLeaning: -0.4,
    emotionalIntensity: 0.8,
    tribalActivation: 0.85,
    threatSignal: 0.7,
    sensationalism: 0.75,
    groupConflict: 0.8,
    biasExplanation: 'Left-leaning editorial framing that clearly positions the opposition claims as false through language choices like "without evidence" in headline and "repeatedly debunked." While factually accurate, the framing itself carries editorial judgment.',
    behaviouralAnalysis: 'Extremely high tribal activation and group conflict scores. The article creates strong in-group/out-group dynamics. Threat signaling is elevated through references to democratic erosion and potential civil unrest.',
    highlightedSentences: [
      'despite election monitors from multiple independent organizations certifying the results',
      'could incite civil unrest',
    ],
  },
  {
    id: '5',
    headline: 'Local Community Garden Program Expands to 50 New Sites',
    publisher: 'Community Herald',
    date: '2026-02-11',
    content: `The city's popular community garden initiative will double in size this spring, with 50 new locations opening across underserved neighborhoods.\n\nThe expansion, funded through a public-private partnership, aims to address food deserts while creating green spaces in urban areas.\n\n"These gardens transform more than just empty lots," said program director Maria Chen. "They build community connections, improve nutrition access, and give residents a sense of ownership over their neighborhoods."\n\nVolunteer applications have already exceeded capacity, with over 2,000 residents signing up for garden plots. The program includes free gardening workshops and seed distribution.`,
    politicalLeaning: -0.15,
    emotionalIntensity: 0.2,
    tribalActivation: 0.05,
    threatSignal: 0.05,
    sensationalism: 0.1,
    groupConflict: 0.05,
    biasExplanation: 'Slightly left-leaning in its framing of community-oriented government programs as unambiguously positive. Minimal bias overall with straightforward reporting of facts and community impact.',
    behaviouralAnalysis: 'Very low activation across all behavioral metrics. The article is positive and community-focused without employing divisive rhetoric or threat-based messaging. A model of constructive journalism.',
    highlightedSentences: [
      'address food deserts while creating green spaces',
    ],
  },
  {
    id: '6',
    headline: 'Immigration Surge Overwhelms Border Processing Centers',
    publisher: 'Frontier Report',
    date: '2026-02-10',
    content: `Border processing facilities are operating at 300% capacity as unprecedented numbers of migrants seek entry, according to leaked internal documents from the border security agency.\n\nThe crisis has prompted emergency resource deployments, with temporary shelters erected in parking lots and processing times stretching to weeks.\n\n"Our personnel are exhausted and our infrastructure is breaking," a senior border official said on condition of anonymity. "We've been warning about this for months."\n\nHumanitarian organizations have criticized conditions at overcrowded facilities, while security hawks demand stricter enforcement measures. The political divide on immigration policy continues to widen.`,
    politicalLeaning: 0.55,
    emotionalIntensity: 0.7,
    tribalActivation: 0.6,
    threatSignal: 0.75,
    sensationalism: 0.65,
    groupConflict: 0.55,
    biasExplanation: 'Right-leaning framing using crisis language ("overwhelms", "surge", "300% capacity"). The use of "leaked documents" and anonymous sources adds urgency. Humanitarian perspectives are included but positioned as secondary to the security narrative.',
    behaviouralAnalysis: 'High threat signaling through crisis framing and infrastructure-failure narratives. Moderate tribal activation with clear political faction references ("humanitarian organizations" vs "security hawks"). Group conflict is elevated by the explicit mention of political divide.',
    highlightedSentences: [
      'operating at 300% capacity',
      'security hawks demand stricter enforcement measures',
    ],
  },
];

export const mockReviewer: Reviewer = {
  id: 'r1',
  name: 'Sarah Mitchell',
  email: 'sarah.m@biaswatch.org',
  reviewCount: 142,
  accuracy: 0.89,
  joinedAt: '2025-06-15',
};

export const mockReviews: Review[] = [
  {
    id: 'rev1',
    articleId: '1',
    reviewerId: 'r1',
    political: 0.3,
    intensity: 0.5,
    sensationalism: 0.35,
    threat: 0.25,
    groupConflict: 0.3,
    comment: 'Subtle framing bias in word choice favoring reform narrative.',
    highlightedSentence: 'Supporters call it a necessary modernization',
    createdAt: '2026-02-15',
  },
];

export const mockReviewQueue: ReviewQueueItem[] = mockArticles.slice(0, 4).map((article, i) => ({
  id: `q${i + 1}`,
  article,
  aiPolitical: article.politicalLeaning,
  aiIntensity: article.emotionalIntensity,
  aiTribal: article.tribalActivation,
  priority: i === 0 ? 'high' : i < 2 ? 'medium' : 'low',
}));

export const mockDashboardStats: DashboardStats = {
  totalArticles: 1247,
  totalReviews: 3891,
  avgPoliticalLeaning: 0.08,
  avgEmotionalIntensity: 0.52,
  avgTribalActivation: 0.38,
  reviewerCount: 64,
  biasDistribution: [
    { label: 'Far Left', value: 8, color: 'hsl(215, 75%, 35%)' },
    { label: 'Left', value: 22, color: 'hsl(215, 75%, 55%)' },
    { label: 'Center-Left', value: 18, color: 'hsl(215, 50%, 65%)' },
    { label: 'Center', value: 24, color: 'hsl(220, 10%, 55%)' },
    { label: 'Center-Right', value: 15, color: 'hsl(0, 50%, 65%)' },
    { label: 'Right', value: 10, color: 'hsl(0, 72%, 55%)' },
    { label: 'Far Right', value: 3, color: 'hsl(0, 72%, 35%)' },
  ],
  intensityDistribution: [
    { range: '0-0.2', count: 180 },
    { range: '0.2-0.4', count: 320 },
    { range: '0.4-0.6', count: 410 },
    { range: '0.6-0.8', count: 250 },
    { range: '0.8-1.0', count: 87 },
  ],
  tribalDistribution: [
    { level: 'None', count: 290 },
    { level: 'Low', count: 380 },
    { level: 'Moderate', count: 340 },
    { level: 'High', count: 170 },
    { level: 'Extreme', count: 67 },
  ],
  timelineData: [
    { date: '2026-01-01', articles: 42, avgBias: 0.12 },
    { date: '2026-01-08', articles: 38, avgBias: -0.05 },
    { date: '2026-01-15', articles: 55, avgBias: 0.18 },
    { date: '2026-01-22', articles: 47, avgBias: 0.08 },
    { date: '2026-01-29', articles: 61, avgBias: -0.1 },
    { date: '2026-02-05', articles: 50, avgBias: 0.15 },
    { date: '2026-02-12', articles: 44, avgBias: 0.02 },
  ],
};
